version: "3.9"

services:
  multibot:
    image: ghcr.io/missemily22/multifunctionbot:main
    container_name: multibot
    environment:
      - CONFIG_FILE_URL = ${CONFIG_FILE_URL}
    ports:
      - 8080:8080
    restart: unless-stopped 
